import { useState, useEffect } from 'react';
import { Settings } from '../types';
import { DEFAULT_SETTINGS } from '../constants/settings';
import { API_ENDPOINTS } from '../constants/api';
import { TIMING } from '../constants/timing';
import { authFetch } from '../utils/api';

export function useSettings() {
  const [settings, setSettings] = useState<Settings>(DEFAULT_SETTINGS);
  const [isSaving, setIsSaving] = useState(false);
  const [saveStatus, setSaveStatus] = useState('');

  useEffect(() => {
    authFetch(API_ENDPOINTS.SETTINGS)
      .then(async res => {
        if (!res.ok) {
          throw new Error(`Failed to load settings (${res.status})`);
        }
        return res.json();
      })
      .then(data => {
        setSettings({
          CLAUDE_MEM_MODEL: data.CLAUDE_MEM_MODEL ?? DEFAULT_SETTINGS.CLAUDE_MEM_MODEL,
          CLAUDE_MEM_CONTEXT_OBSERVATIONS: data.CLAUDE_MEM_CONTEXT_OBSERVATIONS ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_OBSERVATIONS,
          CLAUDE_MEM_WORKER_PORT: data.CLAUDE_MEM_WORKER_PORT ?? DEFAULT_SETTINGS.CLAUDE_MEM_WORKER_PORT,
          CLAUDE_MEM_WORKER_HOST: data.CLAUDE_MEM_WORKER_HOST ?? DEFAULT_SETTINGS.CLAUDE_MEM_WORKER_HOST,

          CLAUDE_MEM_PROVIDER: data.CLAUDE_MEM_PROVIDER ?? DEFAULT_SETTINGS.CLAUDE_MEM_PROVIDER,
          CLAUDE_MEM_GEMINI_API_KEY: data.CLAUDE_MEM_GEMINI_API_KEY ?? DEFAULT_SETTINGS.CLAUDE_MEM_GEMINI_API_KEY,
          CLAUDE_MEM_GEMINI_MODEL: data.CLAUDE_MEM_GEMINI_MODEL ?? DEFAULT_SETTINGS.CLAUDE_MEM_GEMINI_MODEL,
          CLAUDE_MEM_GEMINI_RATE_LIMITING_ENABLED: data.CLAUDE_MEM_GEMINI_RATE_LIMITING_ENABLED ?? DEFAULT_SETTINGS.CLAUDE_MEM_GEMINI_RATE_LIMITING_ENABLED,

          CLAUDE_MEM_OPENROUTER_API_KEY: data.CLAUDE_MEM_OPENROUTER_API_KEY ?? DEFAULT_SETTINGS.CLAUDE_MEM_OPENROUTER_API_KEY,
          CLAUDE_MEM_OPENROUTER_MODEL: data.CLAUDE_MEM_OPENROUTER_MODEL ?? DEFAULT_SETTINGS.CLAUDE_MEM_OPENROUTER_MODEL,
          CLAUDE_MEM_OPENROUTER_SITE_URL: data.CLAUDE_MEM_OPENROUTER_SITE_URL ?? DEFAULT_SETTINGS.CLAUDE_MEM_OPENROUTER_SITE_URL,
          CLAUDE_MEM_OPENROUTER_APP_NAME: data.CLAUDE_MEM_OPENROUTER_APP_NAME ?? DEFAULT_SETTINGS.CLAUDE_MEM_OPENROUTER_APP_NAME,

          CLAUDE_MEM_CONTEXT_SHOW_READ_TOKENS: data.CLAUDE_MEM_CONTEXT_SHOW_READ_TOKENS ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_READ_TOKENS,
          CLAUDE_MEM_CONTEXT_SHOW_WORK_TOKENS: data.CLAUDE_MEM_CONTEXT_SHOW_WORK_TOKENS ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_WORK_TOKENS,
          CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT: data.CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT,
          CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_PERCENT: data.CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_PERCENT ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_PERCENT,

          CLAUDE_MEM_CONTEXT_FULL_COUNT: data.CLAUDE_MEM_CONTEXT_FULL_COUNT ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_FULL_COUNT,
          CLAUDE_MEM_CONTEXT_FULL_FIELD: data.CLAUDE_MEM_CONTEXT_FULL_FIELD ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_FULL_FIELD,
          CLAUDE_MEM_CONTEXT_SESSION_COUNT: data.CLAUDE_MEM_CONTEXT_SESSION_COUNT ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SESSION_COUNT,

          CLAUDE_MEM_CONTEXT_SHOW_LAST_SUMMARY: data.CLAUDE_MEM_CONTEXT_SHOW_LAST_SUMMARY ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_LAST_SUMMARY,
          CLAUDE_MEM_CONTEXT_SHOW_LAST_MESSAGE: data.CLAUDE_MEM_CONTEXT_SHOW_LAST_MESSAGE ?? DEFAULT_SETTINGS.CLAUDE_MEM_CONTEXT_SHOW_LAST_MESSAGE,

          CLAUDE_MEM_MAX_CONCURRENT_AGENTS: data.CLAUDE_MEM_MAX_CONCURRENT_AGENTS ?? DEFAULT_SETTINGS.CLAUDE_MEM_MAX_CONCURRENT_AGENTS,
          CLAUDE_MEM_LLM_QUEUE_MODE: data.CLAUDE_MEM_LLM_QUEUE_MODE ?? DEFAULT_SETTINGS.CLAUDE_MEM_LLM_QUEUE_MODE,
          CLAUDE_MEM_LLM_MIN_SEND_INTERVAL_MS: data.CLAUDE_MEM_LLM_MIN_SEND_INTERVAL_MS ?? DEFAULT_SETTINGS.CLAUDE_MEM_LLM_MIN_SEND_INTERVAL_MS,
          CLAUDE_MEM_LLM_BATCH_MAX_ITEMS: data.CLAUDE_MEM_LLM_BATCH_MAX_ITEMS ?? DEFAULT_SETTINGS.CLAUDE_MEM_LLM_BATCH_MAX_ITEMS,
          CLAUDE_MEM_LLM_BATCH_MAX_CHARS: data.CLAUDE_MEM_LLM_BATCH_MAX_CHARS ?? DEFAULT_SETTINGS.CLAUDE_MEM_LLM_BATCH_MAX_CHARS,
          CLAUDE_MEM_LLM_COALESCE_WINDOW_MS: data.CLAUDE_MEM_LLM_COALESCE_WINDOW_MS ?? DEFAULT_SETTINGS.CLAUDE_MEM_LLM_COALESCE_WINDOW_MS,
          CLAUDE_MEM_LLM_ADAPTIVE_BACKOFF: data.CLAUDE_MEM_LLM_ADAPTIVE_BACKOFF ?? DEFAULT_SETTINGS.CLAUDE_MEM_LLM_ADAPTIVE_BACKOFF,
          CLAUDE_MEM_LLM_MAX_ATTEMPTS: data.CLAUDE_MEM_LLM_MAX_ATTEMPTS ?? DEFAULT_SETTINGS.CLAUDE_MEM_LLM_MAX_ATTEMPTS,
          CLAUDE_MEM_LLM_CONTEXT_SPLIT_ENABLED: data.CLAUDE_MEM_LLM_CONTEXT_SPLIT_ENABLED ?? DEFAULT_SETTINGS.CLAUDE_MEM_LLM_CONTEXT_SPLIT_ENABLED,
          CLAUDE_MEM_LLM_CONTEXT_MAX_CHARS: data.CLAUDE_MEM_LLM_CONTEXT_MAX_CHARS ?? DEFAULT_SETTINGS.CLAUDE_MEM_LLM_CONTEXT_MAX_CHARS,
          CLAUDE_MEM_LLM_CONTEXT_SPLIT_MAX_PARTS: data.CLAUDE_MEM_LLM_CONTEXT_SPLIT_MAX_PARTS ?? DEFAULT_SETTINGS.CLAUDE_MEM_LLM_CONTEXT_SPLIT_MAX_PARTS,
          CLAUDE_MEM_QUEUE_HIGH_WATERMARK: data.CLAUDE_MEM_QUEUE_HIGH_WATERMARK ?? DEFAULT_SETTINGS.CLAUDE_MEM_QUEUE_HIGH_WATERMARK,
          CLAUDE_MEM_QUEUE_CRITICAL_WATERMARK: data.CLAUDE_MEM_QUEUE_CRITICAL_WATERMARK ?? DEFAULT_SETTINGS.CLAUDE_MEM_QUEUE_CRITICAL_WATERMARK,
          CLAUDE_MEM_QUEUE_DROP_POLICY: data.CLAUDE_MEM_QUEUE_DROP_POLICY ?? DEFAULT_SETTINGS.CLAUDE_MEM_QUEUE_DROP_POLICY,
          CLAUDE_MEM_QUEUE_METRICS_ENABLED: data.CLAUDE_MEM_QUEUE_METRICS_ENABLED ?? DEFAULT_SETTINGS.CLAUDE_MEM_QUEUE_METRICS_ENABLED,
        });
      })
      .catch(error => {
        console.error('Failed to load settings:', error);
      });
  }, []);

  const saveSettings = async (newSettings: Settings) => {
    setIsSaving(true);
    setSaveStatus('Saving...');

    try {
      const response = await authFetch(API_ENDPOINTS.SETTINGS, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(newSettings)
      });

      if (!response.ok) {
        setSaveStatus(`✗ Error: ${response.status === 401 ? 'Unauthorized' : response.statusText}`);
        setIsSaving(false);
        return;
      }

      const result = await response.json();

      if (result.success) {
        setSettings(newSettings);
        setSaveStatus('✓ Saved');
        setTimeout(() => setSaveStatus(''), TIMING.SAVE_STATUS_DISPLAY_DURATION_MS);
      } else {
        setSaveStatus(`✗ Error: ${result.error}`);
      }
    } catch (error) {
      setSaveStatus(`✗ Error: ${error instanceof Error ? error.message : 'Network error'}`);
    }

    setIsSaving(false);
  };

  return { settings, saveSettings, isSaving, saveStatus };
}
